### ISSUE TITLE
I'm getting a System.OperationCanceledException after the socket has been open for a couple minutes

### ISSUE THREAD

**Issue by NullVoxPopuli** [coinigy/PureWebSockets#6] opened 2018-04-03 10:07 UTC
any ideas as to what could cause that and how to best handle that type of exception?

I have on data and on error bound, and this is what I'm seeing in the console:

```
socket on data: [||]
socket error: System.OperationCanceledException: The operation was canceled.
   at System.Collections.Concurrent.BlockingCollection`1.TryTakeWithNoTimeValidation(T& item, Int32 millisecondsTimeout, CancellationToken cancellationToken, CancellationTokenSource combinedTokenSource)
   at System.Collections.Concurrent.BlockingCollection`1.TryTake(T& item, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Collections.Concurrent.BlockingCollection`1.Take(CancellationToken cancellationToken)
   at PureWebSockets.PureWebSocket.<<StartSender>b__82_0>d.MoveNext()
sending: "{"action":"ping"}"
OnMessage: "{"h":["42fb65370a943df3.public","2","pong"],"d":[]}"
```

the trace makes me think it has to do with sending, but I don't know how, given that my printfn for "sending" comes bofere actual sending.
Note that I'm using F#, so `[||]`  is just a fixed size array (where the size is 0). `[]` would be a list of size 0

**Comment by ByronAP** [comment] 2018-04-17 20:34
"socket on data: [||]" that seems illegal, what is that?

**Comment by NullVoxPopuli** [comment] 2018-04-17 20:36
that was what I was getting in the data hook

**Comment by ByronAP** [comment] 2018-04-18 01:11
any way you can strip this issue into something reproducible for me? like taking the basics from your project and putting them into a repo.

**Comment by ByronAP** [comment] 2018-05-10 20:59
closing since I can not reproduce

**Closed as completed by ByronAP** 2018-05-10 20:59 UTC
