### ISSUE TITLE
Unable to rad data from the transport connection: Broken Pipe

### ISSUE THREAD

**Issue by senzacionale** [coinigy/PureWebSockets#13] opened 2019-03-02 06:42 UTC
I am getting strange error with PureWebSockets library, Any idea?

`[23:44:34 ERR] The remote party closed the WebSocket connection without completing the close handshake.
System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake. ---> System.IO.IOException: Unable to read data from the transport connection: Broken pipe. ---> System.Net.Sockets.SocketException: Broken pipe
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStreamInternal.<WriteSingleChunk>g__CompleteAsync|36_1[TWriteAdapter](ValueTask writeTask, Byte[] bufferToReturn)
   at System.Net.Security.SslStreamInternal.<WriteAsyncInternal>g__ExitWriteAsync|35_0[TWriteAdapter](ValueTask task)
   at System.Net.WebSockets.ManagedWebSocket.SendFrameFallbackAsync(MessageOpcode opcode, Boolean endOfMessage, ReadOnlyMemory`1 payloadBuffer, CancellationToken cancellationToken)
   at System.Net.WebSockets.ManagedWebSocket.SendFrameFallbackAsync(MessageOpcode opcode, Boolean endOfMessage, ReadOnlyMemory`1 payloadBuffer, CancellationToken cancellationToken)
   at PureWebSockets.PureWebSocket.<StartSender>b__58_0()`
and then
```

2019-03-01T22:23:56.8416806+00:00 PureWebSocket.StartMonitor: Exiting monitor.
2019-03-01T22:23:56.8417489+00:00 PureWebSocket.Disconnect: Disconnect threw exception: Object reference not set to an instance of an object..
2019-03-01T22:23:56.8417618+00:00 PureWebSocket.Disconnect: Disconnect called, closing websocket.
2019-03-01T22:23:56.8417684+00:00 PureWebSocket.Dispose: Dispose called, with waitForSendsToComplete = True.
2019-03-01T22:23:56.8417745+00:00 PureWebSocket.StartMonitor: State changed from Connecting to Closed.
2019-03-01T22:23:56.9328720+00:00 PureWebSocket.StartSender: Exiting sender.
2019-03-01T22:23:56.9329360+00:00 PureWebSocket.StartSender: Entering sender loop.
2019-03-01T22:23:56.9329440+00:00 PureWebSocket.StartSender: Starting sender.
2019-03-01T22:23:56.9329570+00:00 PureWebSocket.StartListener: Listener exiting
2019-03-01T22:23:56.9329820+00:00 PureWebSocket.StartListener: Entering listener loop.
2019-03-01T22:23:56.9329973+00:00 PureWebSocket.StartListener: Starting listener.
2019-03-01T22:23:56.9330084+00:00 PureWebSocket.Connect: Starting tasks.
```

**Comment by ByronAP** [comment] 2019-03-17 20:15
This looks like the remote host closed the connection midstream. This unfortunately happens. To be sure though I would need a reproduction test case.

**Comment by ByronAP** [comment] 2019-03-17 20:16
event bug fix will be released shortly btw

**Comment by ByronAP** [comment] 2019-03-25 16:17
closing for now, if it comes back up as a bug after #12 will reopen

**Closed as completed by ByronAP** 2019-03-25 16:17 UTC
